spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true # hibernate ? ??? ??? ? data.sql ? ????? ??.

jwt:
  header: Authorization
  secret: asdajdhdfsdjhfsjdhfsjhdfsjdhfwueryywuyereuwyrqwehqwjehqjklklklklklklklklklklklkwehqjwhdzjhcjzxchzjxchasd
  access-token-validity-in-seconds: 600 # 10 min
  refresh-token-validity-in-seconds: 86400 # 24 hour # ??? ?? ?? ? 1?
